name: asmr_downloader
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  collection: ^1.18.0
  dio: ^5.7.0
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.4
  flutter_riverpod: ^2.5.1
  logger: ^2.4.0
  path: ^1.9.0
  path_provider: ^2.1.4
  window_manager: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.18.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.7
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true
